services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    restart: unless-stopped
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks: [ragnet]

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"  
      - "6334:6334"   
    volumes:
      - qdrant_data:/qdrant/storage
    networks: [ragnet]

  flowise:
    image: flowiseai/flowise:latest
    container_name: flowise
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      # login opcional
      - FLOWISE_USERNAME=admin
      - FLOWISE_PASSWORD=admin123

      # conecta no Qdrant (via rede docker, use o hostname do serviço)
      - QDRANT_URL=http://qdrant:6333

      # aponta pro Ollama
      - OLLAMA_BASE_URL=http://ollama:11434

      # dados do Flowise
      - FLOWISE_FILE_STORAGE_PATH=/root/.flowise
    volumes:
      - flowise_data:/root/.flowise
    depends_on:
      - ollama
      - qdrant
    networks: [ragnet]

volumes:
  ollama_data:
    driver: local
  qdrant_data:
    driver: local
  flowise_data:
    driver: local

networks:  # precisam estar na mesma rede
  ragnet:
    driver: bridge